<?php
use Illuminate\Database\Seeder;
class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $product = new \App\Product();
        $product->id = "1";
        $product->name = "BELL PEPPER";
        $product->productType_id = "1";
        $product->description = "Ớt xanh xào với thịt bò là ngon nhất";
        $product->unit_price = "12000";
        $product->promotion_price = "8000";
        $product->image = "product-1.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "2";
        $product->name = "STRAWBERRY";
        $product->productType_id = "2";
        $product->description = "Dâu tây chín đỏ ngon ngất ngây";
        $product->unit_price = "12000";
        $product->promotion_price = "0";
        $product->image = "product-2.jpg";
        $product->unit = "quả";
        $product->save();
        $product = new \App\Product();
        $product->id = "3";
        $product->name = "GREEN BEANS";
        $product->productType_id = "1";
        $product->description = "Đậu Hà Lan bán theo lạng";
        $product->unit_price = "12000";
        $product->promotion_price = "0";
        $product->image = "product-3.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "4";
        $product->name = "PURPLE CABBAGE";
        $product->productType_id = "1";
        $product->description = "Bắp cải tím";
        $product->unit_price = "18000";
        $product->promotion_price = "16000";
        $product->image = "product-4.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "5";
        $product->name = "TOMATOE";
        $product->productType_id = "1";
        $product->description = "Cà chua đỏ mọng";
        $product->unit_price = "14000";
        $product->promotion_price = "10000";
        $product->image = "product-5.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "6";
        $product->name = "BROCOLLI";
        $product->productType_id = "1";
        $product->description = "Xúp lơ xanh";
        $product->unit_price = "20000";
        $product->promotion_price = "15000";
        $product->image = "product-6.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "7";
        $product->name = "CARROTS";
        $product->productType_id = "1";
        $product->description = "Cà rốt";
        $product->unit_price = "8000";
        $product->promotion_price = "0";
        $product->image = "product-7.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "8";
        $product->name = "FRUIT JUICE";
        $product->productType_id = "3";
        $product->description = "Nước ép hoa quả";
        $product->unit_price = "30000";
        $product->promotion_price = "0";
        $product->image = "product-8.jpg";
        $product->unit = "nước ép";
        $product->save();
        $product = new \App\Product();
        $product->id = "9";
        $product->name = "ONION";
        $product->productType_id = "1";
        $product->description = "Hành tây";
        $product->unit_price = "15000";
        $product->promotion_price = "0";
        $product->image = "product-9.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "10";
        $product->name = "APPLE";
        $product->productType_id = "2";
        $product->description = "quả táo";
        $product->unit_price = "30000";
        $product->promotion_price = "29000";
        $product->image = "product-10.jpg";
        $product->unit = "quả";
        $product->save();
        $product = new \App\Product();
        $product->id = "11";
        $product->name = "GARLIC";
        $product->productType_id = "1";
        $product->description = "hành ta";
        $product->unit_price = "10000";
        $product->promotion_price = "0";
        $product->image = "product-11.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "12";
        $product->name = "CHILLI";
        $product->productType_id = "1";
        $product->description = "Ớt";
        $product->unit_price = "4000";
        $product->promotion_price = "0";
        $product->image = "product-12.jpg";
        $product->unit = "rau củ";
        $product->save();
        $product = new \App\Product();
        $product->id = "13";
        $product->name = "BEAN";
        $product->productType_id = "4";
        $product->description = "đậu đỏ";
        $product->unit_price = "17000";
        $product->promotion_price = "15000";
        $product->image = "product-13.jpg";
        $product->unit = "hạt";
        $product->save();
    }
}
